import javax.swing.*;
import java.awt.*;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SendFragment extends JFrame {
    private JPanel sendFragment;
    private JTextPane textPane_contacts;
    private JTextPane textPane_id;
    private JTextPane textPane_amount;
    private JTextPane textPane_description;
    private JButton button_send;
    private JButton button_backAnswer;
    private OnlineTransactionPayPayOk onlineTransactionPayPayOk;
    private AnswerFragment answerFragment;
    private DialogForm dialog;

    public SendFragment() {
        setContentPane(sendFragment);
        setTitle("PayPayOK - система взаимодействия");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(750, 550);
        setLocationRelativeTo(null);
        setVisible(true);
        onlineTransactionPayPayOk = new OnlineTransactionPayPayOk("https://pay.pay-ok.org/demo/?REQ");
        button_send.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialog = new DialogForm("Информация о регистрации чека");
                dialog.setVisibleOK();
                dialog.setTextPane(//TODO проверить работу dialog.setTextPanel
                        onlineTransactionPayPayOk.sendCheck4Registration(
                                textPane_contacts.getText(),
                                textPane_id.getText(),
                                textPane_amount.getText().replace(",", "").replace(".", ""),
                                textPane_description.getText()
                        ));
            }
        });
        button_backAnswer.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                dialog = new DialogForm("Информация о зарегестрированных чеках");
                dialog.setVisibleGET();
                //  answerFragment = new AnswerFragment();
            }
        });
    }

    private boolean dataCheck() {
        if (textPane_id.getText().chars().allMatch(Character::isDigit))
            return true;
        return false; //TODO посмотреть при указании запятой или точки данные не отправляются
    }

    public static void main(String[] args) {
        new SendFragment();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        sendFragment = new JPanel();
        sendFragment.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        sendFragment.setBackground(new Color(-15275521));
        sendFragment.setEnabled(false);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-12583681));
        label1.setForeground(new Color(-16777216));
        label1.setText("Контактные данные");
        sendFragment.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-1));
        label2.setText("Номер л\\с");
        sendFragment.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setBackground(new Color(-1));
        label3.setText("Итого");
        sendFragment.add(label3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setBackground(new Color(-1));
        label4.setText("Описание");
        sendFragment.add(label4, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textPane_contacts = new JTextPane();
        textPane_contacts.setBackground(new Color(-1));
        textPane_contacts.setEnabled(true);
        sendFragment.add(textPane_contacts, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        textPane_id = new JTextPane();
        textPane_id.setBackground(new Color(-1));
        sendFragment.add(textPane_id, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        textPane_amount = new JTextPane();
        textPane_amount.setBackground(new Color(-1));
        sendFragment.add(textPane_amount, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        textPane_description = new JTextPane();
        textPane_description.setBackground(new Color(-1));
        sendFragment.add(textPane_description, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        button_send = new JButton();
        button_send.setBackground(new Color(-1));
        button_send.setText("Отправить");
        sendFragment.add(button_send, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button_backAnswer = new JButton();
        button_backAnswer.setBackground(new Color(-1));
        button_backAnswer.setText("Перейти в получению чека");
        sendFragment.add(button_backAnswer, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return sendFragment;
    }
}
